In [3]:
import numpy as np
import pandas as pd

In [4]:
df = pd.DataFrame({'text': ['people watch campusx', 'campusx watch campusx', 'people write comment', 'campusx write comment'], 'output': [1, 1, 0, 0]})

In [5]:
df

,text,output
0,people watch campusx,1
1,campusx watch campusx,1
2,people write comment,0
3,campusx write comment,0


In [6]:
from sklearn.feature_extraction.text import CountVectorizer

In [7]:
cv = CountVectorizer()

In [10]:
bow = cv.fit_transform(df['text'])

In [12]:
cv.vocabulary_

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}

In [13]:
bow[0].toarray()

array([[1, 0, 1, 1, 0]])

In [15]:
cv.transform(["campusx watch and write comment of campusx"]).toarray()

array([[2, 1, 0, 1, 1]])

In [1]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()

In [8]:
tfVector = tfidf.fit_transform(df['text']).toarray()

In [10]:
tfVector, tfVector.shape

(array([[0.49681612, 0.        , 0.61366674, 0.61366674, 0.        ],
        [0.8508161 , 0.        , 0.        , 0.52546357, 0.        ],
        [0.        , 0.57735027, 0.57735027, 0.        , 0.57735027],
        [0.49681612, 0.61366674, 0.        , 0.        , 0.61366674]]),
 (4, 5))

In [14]:
tfidf.idf_,tfidf.get_feature_names_out()

(array([1.22314355, 1.51082562, 1.51082562, 1.51082562, 1.51082562]),
 array(['campusx', 'comment', 'people', 'watch', 'write'], dtype=object))