In [3]:
import os
import gensim
from gensim.models import word2vec, KeyedVectors

In [9]:
model = KeyedVectors.load_word2vec_format(r'Data/GoogleNews-vectors-negative300.bin.gz', binary=True, limit=500000)

In [10]:
model['cricket']

array([-3.67187500e-01, -1.21582031e-01,  2.85156250e-01,  8.15429688e-02,
        3.19824219e-02, -3.19824219e-02,  1.34765625e-01, -2.73437500e-01,
        9.46044922e-03, -1.07421875e-01,  2.48046875e-01, -6.05468750e-01,
        5.02929688e-02,  2.98828125e-01,  9.57031250e-02,  1.39648438e-01,
       -5.41992188e-02,  2.91015625e-01,  2.85156250e-01,  1.51367188e-01,
       -2.89062500e-01, -3.46679688e-02,  1.81884766e-02, -3.92578125e-01,
        2.46093750e-01,  2.51953125e-01, -9.86328125e-02,  3.22265625e-01,
        4.49218750e-01, -1.36718750e-01, -2.34375000e-01,  4.12597656e-02,
       -2.15820312e-01,  1.69921875e-01,  2.56347656e-02,  1.50146484e-02,
       -3.75976562e-02,  6.95800781e-03,  4.00390625e-01,  2.09960938e-01,
        1.17675781e-01, -4.19921875e-02,  2.34375000e-01,  2.03125000e-01,
       -1.86523438e-01, -2.46093750e-01,  3.12500000e-01, -2.59765625e-01,
       -1.06933594e-01,  1.04003906e-01, -1.79687500e-01,  5.71289062e-02,
       -7.41577148e-03, -

In [14]:
model['cricket'].shape

(300,)

In [15]:
model.most_similar('facebook')

[('Facebook', 0.7563533186912537),
 ('FaceBook', 0.7076998949050903),
 ('twitter', 0.6988552212715149),
 ('myspace', 0.6941817998886108),
 ('Twitter', 0.664244532585144),
 ('Facebook.com', 0.6529868245124817),
 ('FacebookFacebook', 0.6162722110748291),
 ('facebook.com', 0.6135972142219543),
 ('Twitter.com', 0.6102108359336853),
 ('TwitterTwitter', 0.6085205674171448)]

In [17]:
model.similarity('man', 'men')

np.float32(0.5489763)

In [18]:
model.similarity('man', 'PHP')

np.float32(-0.032995153)

In [19]:
model.doesnt_match(['PHP', 'java', 'monkey'])

'monkey'

## Training own Model

In [2]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [14]:
story = []
for filename in os.listdir(r'Data/GamesOfThrones'):
    f = open(os.path.join('Data/GamesOfThrones', filename), encoding='latin-1')
    corpus = f.read()
    raw_sent = sent_tokenize(corpus)
    
    for sent in raw_sent:
        story.append(simple_preprocess(sent))

In [18]:
story

[['storm',
  'of',
  'swords',
  'book',
  'three',
  'of',
  'song',
  'of',
  'ice',
  'and',
  'fire',
  'by',
  'george'],
 ['martin',
  'note',
  'on',
  'chronology',
  'song',
  'of',
  'ice',
  'and',
  'fire',
  'is',
  'told',
  'through',
  'the',
  'eyes',
  'of',
  'characters',
  'who',
  'are',
  'sometimes',
  'hundreds',
  'or',
  'even',
  'thousands',
  'of',
  'miles',
  'apart',
  'from',
  'one',
  'another'],
 ['some',
  'chapters',
  'cover',
  'day',
  'some',
  'only',
  'an',
  'hour',
  'others',
  'might',
  'span',
  'fortnight',
  'month',
  'half',
  'year'],
 ['with',
  'such',
  'structure',
  'the',
  'narrative',
  'cannot',
  'be',
  'strictly',
  'sequential',
  'sometimes',
  'important',
  'things',
  'are',
  'happening',
  'simultaneously',
  'thousand',
  'leagues',
  'apart'],
 ['in',
  'the',
  'case',
  'of',
  'the',
  'volume',
  'now',
  'in',
  'hand',
  'the',
  'reader',
  'should',
  'realize',
  'that',
  'the',
  'opening',
  'chap

In [19]:
len(story)

145020

In [22]:
model = gensim.models.Word2Vec(
    window=10,
    min_count=2
)

In [23]:
model.build_vocab(story)

In [24]:
model.train(story, total_examples=model.corpus_count, epochs=model.epochs)

(6570465, 8628190)

In [29]:
model.wv.most_similar('queen')

[('princess', 0.7420772910118103),
 ('margaery', 0.6915709376335144),
 ('daenerys', 0.6897676587104797),
 ('cersei', 0.6798440217971802),
 ('prince', 0.6554971933364868),
 ('targaryen', 0.649296224117279),
 ('mother', 0.6359758377075195),
 ('stormborn', 0.6305001974105835),
 ('joffrey', 0.623916506767273),
 ('myrcella', 0.6217859983444214)]

In [30]:
model.wv.doesnt_match(['jon', 'rikon', 'robb', 'arya', 'sansa', 'bran'])

'jon'

In [32]:
model.wv['king']

array([ 1.51265   ,  1.0246325 , -1.4045793 ,  2.4083319 , -1.4150428 ,
       -1.1408298 ,  1.6278191 ,  1.8680526 , -3.4692156 ,  0.33286586,
       -0.76457787, -2.619756  ,  0.15862633,  1.2143937 , -3.4895227 ,
       -0.16524212,  0.57752675,  2.0103137 , -1.2140894 , -0.05535822,
       -0.23309453,  0.3024851 ,  3.4306815 , -3.4860165 , -2.474758  ,
       -0.5893093 , -2.0789752 , -1.0650475 , -0.813968  ,  2.0794    ,
       -1.4186181 ,  2.0849438 ,  0.94094545, -0.11124951, -0.64401114,
       -0.9000272 , -1.0737953 , -0.5115462 ,  2.3727639 , -2.3423176 ,
        0.36158416,  1.437589  ,  3.143647  ,  0.726451  , -1.0669798 ,
       -1.7352619 ,  0.5147562 , -2.2000365 ,  4.140276  , -3.636417  ,
       -3.295967  , -0.785692  , -0.4870825 , -2.4456837 ,  3.3942122 ,
       -0.96245146, -0.6204994 , -0.13279098,  1.9864792 ,  1.2679467 ,
        1.7890877 ,  1.2301997 ,  0.18926436,  1.484021  ,  0.65311015,
        0.74261594, -2.0225947 , -0.36101806, -1.258164  , -3.24

In [33]:
model.wv.similarity('arya', 'sansa')

np.float32(0.8507173)

In [34]:
model.wv.similarity('tywin', 'sansa')

np.float32(0.21891595)

In [35]:
model.wv.get_normed_vectors()

array([[ 0.02394853, -0.09928109,  0.03303447, ..., -0.03261686,
        -0.08423471,  0.09974037],
       [-0.08178785, -0.21908228,  0.07738341, ..., -0.05415023,
        -0.21488251,  0.11974564],
       [ 0.24019754, -0.0243242 , -0.15450332, ..., -0.07673152,
         0.06799629, -0.10717694],
       ...,
       [ 0.03900234,  0.09180316, -0.2581013 , ..., -0.06625322,
         0.15562949, -0.04160527],
       [ 0.01482526, -0.0097283 ,  0.03235356, ...,  0.00554029,
        -0.08979618,  0.10029971],
       [ 0.09070135, -0.06803884, -0.11177964, ...,  0.14281283,
        -0.12582803,  0.15536188]], shape=(17453, 100), dtype=float32)

In [43]:
y = model.wv.index_to_key

In [37]:
from sklearn.decomposition import PCA

In [38]:
pca = PCA(n_components=3)

In [39]:
X = pca.fit_transform(model.wv.get_normed_vectors())

In [40]:
X.shape

(17453, 3)

In [41]:
import plotly.express as px

In [48]:
fig = px.scatter_3d(X[:100], x=0, y=1, z=2, color=y[:100])
fig.show()

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed