In [1]:
import os
import gensim
from gensim.models import word2vec, KeyedVectors

In [2]:
model = KeyedVectors.load_word2vec_format(r'Data/GoogleNews-vectors-negative300.bin.gz', binary=True, limit=500000)

In [3]:
model['cricket']

array([-3.67187500e-01, -1.21582031e-01,  2.85156250e-01,  8.15429688e-02,
        3.19824219e-02, -3.19824219e-02,  1.34765625e-01, -2.73437500e-01,
        9.46044922e-03, -1.07421875e-01,  2.48046875e-01, -6.05468750e-01,
        5.02929688e-02,  2.98828125e-01,  9.57031250e-02,  1.39648438e-01,
       -5.41992188e-02,  2.91015625e-01,  2.85156250e-01,  1.51367188e-01,
       -2.89062500e-01, -3.46679688e-02,  1.81884766e-02, -3.92578125e-01,
        2.46093750e-01,  2.51953125e-01, -9.86328125e-02,  3.22265625e-01,
        4.49218750e-01, -1.36718750e-01, -2.34375000e-01,  4.12597656e-02,
       -2.15820312e-01,  1.69921875e-01,  2.56347656e-02,  1.50146484e-02,
       -3.75976562e-02,  6.95800781e-03,  4.00390625e-01,  2.09960938e-01,
        1.17675781e-01, -4.19921875e-02,  2.34375000e-01,  2.03125000e-01,
       -1.86523438e-01, -2.46093750e-01,  3.12500000e-01, -2.59765625e-01,
       -1.06933594e-01,  1.04003906e-01, -1.79687500e-01,  5.71289062e-02,
       -7.41577148e-03, -

In [4]:
model['cricket'].shape

(300,)

In [5]:
model.most_similar('facebook')

[('Facebook', 0.7563533186912537),
 ('FaceBook', 0.7076998949050903),
 ('twitter', 0.6988552212715149),
 ('myspace', 0.6941817998886108),
 ('Twitter', 0.664244532585144),
 ('Facebook.com', 0.6529868245124817),
 ('FacebookFacebook', 0.6162722110748291),
 ('facebook.com', 0.6135972142219543),
 ('Twitter.com', 0.6102108359336853),
 ('TwitterTwitter', 0.6085205674171448)]

In [6]:
model.similarity('man', 'men')

np.float32(0.5489763)

In [7]:
model.similarity('man', 'PHP')

np.float32(-0.032995153)

In [8]:
model.doesnt_match(['PHP', 'java', 'monkey'])

'monkey'

## Training own Model

In [9]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [10]:
story = []
for filename in os.listdir(r'Data/GamesOfThrones'):
    f = open(os.path.join('Data/GamesOfThrones', filename), encoding='latin-1')
    corpus = f.read()
    raw_sent = sent_tokenize(corpus)
    
    for sent in raw_sent:
        story.append(simple_preprocess(sent))

In [11]:
story

[['storm',
  'of',
  'swords',
  'book',
  'three',
  'of',
  'song',
  'of',
  'ice',
  'and',
  'fire',
  'by',
  'george'],
 ['martin',
  'note',
  'on',
  'chronology',
  'song',
  'of',
  'ice',
  'and',
  'fire',
  'is',
  'told',
  'through',
  'the',
  'eyes',
  'of',
  'characters',
  'who',
  'are',
  'sometimes',
  'hundreds',
  'or',
  'even',
  'thousands',
  'of',
  'miles',
  'apart',
  'from',
  'one',
  'another'],
 ['some',
  'chapters',
  'cover',
  'day',
  'some',
  'only',
  'an',
  'hour',
  'others',
  'might',
  'span',
  'fortnight',
  'month',
  'half',
  'year'],
 ['with',
  'such',
  'structure',
  'the',
  'narrative',
  'cannot',
  'be',
  'strictly',
  'sequential',
  'sometimes',
  'important',
  'things',
  'are',
  'happening',
  'simultaneously',
  'thousand',
  'leagues',
  'apart'],
 ['in',
  'the',
  'case',
  'of',
  'the',
  'volume',
  'now',
  'in',
  'hand',
  'the',
  'reader',
  'should',
  'realize',
  'that',
  'the',
  'opening',
  'chap

In [12]:
len(story)

145020

In [13]:
model = gensim.models.Word2Vec(
    window=10,
    min_count=2
)

In [14]:
model.build_vocab(story)

In [15]:
model.train(story, total_examples=model.corpus_count, epochs=model.epochs)

(6570981, 8628190)

In [16]:
model.wv.most_similar('queen')

[('margaery', 0.7608857750892639),
 ('princess', 0.7505174279212952),
 ('daenerys', 0.7194371223449707),
 ('joffrey', 0.6770880222320557),
 ('myrcella', 0.6747580766677856),
 ('prince', 0.6709061861038208),
 ('elia', 0.6483027338981628),
 ('mother', 0.6435063481330872),
 ('cersei', 0.6370989680290222),
 ('viserys', 0.6140456199645996)]

In [17]:
model.wv.doesnt_match(['jon', 'rikon', 'robb', 'arya', 'sansa', 'bran'])

'jon'

In [18]:
model.wv['king']

array([ 0.637849  ,  1.1459645 ,  1.0245533 ,  2.5641348 , -2.569575  ,
        0.31359366,  0.11650658,  1.5025952 , -2.3447292 , -0.05458373,
        0.30116695, -1.1268666 ,  0.10353897,  1.7344624 , -4.030734  ,
       -3.3402498 , -0.35531685,  1.2649647 , -0.35993358, -1.2828697 ,
        1.2529333 ,  1.5714288 ,  2.0863173 , -2.599372  , -1.5682839 ,
        0.33255157, -2.4808419 , -1.8856581 , -0.8387941 ,  1.3687962 ,
       -0.7075698 ,  0.65993655,  0.19426496, -1.1177562 ,  0.83730036,
       -2.925671  , -2.0848608 ,  1.6288943 ,  1.3389039 , -3.029648  ,
        1.843414  ,  2.160183  ,  3.027659  ,  0.07277171, -0.02801719,
       -0.94171846,  1.0394771 , -3.9921637 ,  3.0505536 , -1.5906072 ,
       -3.3711598 , -2.0649788 , -1.0937545 , -3.802158  ,  2.8584404 ,
        0.19468   ,  0.5750329 , -0.1508293 ,  2.147571  ,  1.0714475 ,
        0.8243631 ,  2.321158  ,  0.58661735,  1.4196999 ,  0.5115969 ,
        0.80995226, -1.5047115 , -0.52849346, -0.5876847 , -2.63

In [19]:
model.wv.similarity('arya', 'sansa')

np.float32(0.8605861)

In [20]:
model.wv.similarity('tywin', 'sansa')

np.float32(0.22999232)

In [21]:
model.wv.get_normed_vectors()

array([[-0.0761144 , -0.13439883,  0.11455289, ..., -0.0618855 ,
        -0.15792134,  0.0696943 ],
       [-0.01857122, -0.13382621, -0.05870793, ..., -0.05200857,
        -0.12548898,  0.15155725],
       [ 0.12064141, -0.10597048, -0.10183538, ...,  0.02857836,
         0.02647539, -0.15849714],
       ...,
       [ 0.13130395,  0.05146559, -0.10774627, ..., -0.12166645,
         0.11346756, -0.13188379],
       [ 0.00848535,  0.02378896,  0.04284415, ..., -0.04444614,
         0.01528976,  0.01347944],
       [ 0.01806591, -0.11389335,  0.07116558, ...,  0.14353572,
        -0.07965117,  0.0357784 ]], shape=(17453, 100), dtype=float32)

In [22]:
y = model.wv.index_to_key

In [23]:
from sklearn.decomposition import PCA

In [24]:
pca = PCA(n_components=3)

In [25]:
X = pca.fit_transform(model.wv.get_normed_vectors())

In [26]:
X.shape

(17453, 3)

In [27]:
import plotly.express as px

In [ ]:
fig = px.scatter_3d(X[:100], x=0, y=1, z=2, color=y[:100])
fig.show()